docs/UserGuide.adoc
Modify repoURL, Introduction, Command Format
=> Add Data Management features to User Guide

docs/UserGuide.adoc
=> Update verification section of user guide

.gitignore, data/modules_cs.json
=> Add JSON data for CS modules

src/main/java/seedu/address/logic/commands/EditCommand.java, src/main/java/seedu/address/logic/parser/AddCommandParser.java, src/main/java/seedu/address/logic/parser/EditCommandParser.java, src/main/java/seedu/address/logic/parser/ParserUtil.java, src/main/java/seedu/address/model/module/Module.java, src/main/java/seedu/address/model/person/Person.java, src/main/java/seedu/address/model/tag/Default.java, src/main/java/seedu/address/model/tag/DefaultTag.java, src/main/java/seedu/address/model/tag/Tag.java, src/main/java/seedu/address/model/tag/TagList.java, src/main/java/seedu/address/model/tag/UserTag.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/storage/JsonAdaptedPerson.java, src/main/java/seedu/address/storage/JsonAdaptedTag.java, src/main/java/seedu/address/ui/PersonCard.java, src/test/java/seedu/address/logic/parser/AddCommandParserTest.java, src/test/java/seedu/address/logic/parser/EditCommandParserTest.java, src/test/java/seedu/address/logic/parser/ParserUtilTest.java, src/test/java/seedu/address/model/tag/TagTest.java, src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java, src/test/java/seedu/address/testutil/PersonBuilder.java, src/test/java/seedu/address/testutil/PersonUtil.java
Change Tag class to an interface.
Add Default Enum, DefaultTag, TagList and UserTag.
=> Refactor Tag Class.

data/modules_cs.json, src/main/java/seedu/address/logic/parser/CheckCommandParser.java, src/main/java/seedu/address/model/ModuleInfo.java, src/test/data/JsonModulesInfoStorageTest/ExtraValuesModulesInfo.json, src/test/data/JsonModulesInfoStorageTest/TypicalModulesInfo.json, src/test/java/seedu/address/storage/JsonModulesInfoStorageTest.java
Add module name to `modules_cs.json` cos I somehow forgot to include it previously.
=> Add module information

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/ModuleInfo.java, src/main/java/seedu/address/model/ModulesInfo.java, src/main/java/seedu/address/model/PrereqLeaf.java, src/main/java/seedu/address/model/PrereqNode.java, src/main/java/seedu/address/storage/JsonModulesInfoStorage.java, src/test/java/seedu/address/model/ModuleInfoTest.java, src/test/java/seedu/address/model/ModulesInfoTest.java, src/test/java/seedu/address/storage/JsonModulesInfoStorageTest.java, src/test/java/seedu/address/testutil/TypicalModulesInfo.java
Added tests also, no change to anything else. Ready to be merged.
`ModulesInfo` has these methods:
* `find(String moduleCode)` -- returns `ModuleInfo` with the given module code, otherwise `null` if not found
* `verify(String moduleCode, List<String> prevSemModuleCodes)` -- returns `true` if the module can be satisfied by taking those given modules in previous semesters, otherwise `false`
=> Change ModuleInfo to use HashMap

.gitignore
If you still have `data/addressbook.json` pls delete and don't commit!
=> Change .gitignore to exclude data/moduleplanner.json

src/main/java/seedu/address/MainApp.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ModuleInfo.java, src/main/java/seedu/address/model/ModulePlanner.java, src/main/java/seedu/address/model/ReadOnlyModulePlanner.java, src/main/java/seedu/address/model/module/Module.java, src/main/java/seedu/address/model/semester/Semester.java, src/main/java/seedu/address/model/studyplan/StudyPlan.java, src/main/java/seedu/address/model/studyplan/UniqueStudyPlanList.java, src/main/java/seedu/address/model/tag/UniqueTagList.java, src/main/java/seedu/address/model/util/SampleDataUtil.java, src/main/java/seedu/address/model/versiontracking/StudyPlanCommitManagerList.java, src/main/java/seedu/address/storage/JsonAdaptedStudyPlan.java, src/main/java/seedu/address/storage/JsonModulePlannerStorage.java, src/main/java/seedu/address/storage/JsonSerializableModulePlanner.java, src/main/java/seedu/address/storage/ModulePlannerStorage.java, src/main/java/seedu/address/storage/Storage.java, src/main/java/seedu/address/storage/StorageManager.java
TODO: need to get a list of default tags from ModulesInfo
=> Include version tracking manager in storage, and implement activate()

src/main/java/seedu/address/model/util/SampleDataUtil.java
=> minor bug fix

src/main/java/seedu/address/logic/parser/ModulePlannerParser.java, src/main/java/seedu/address/model/ModulePlanner.java, src/main/java/seedu/address/model/module/Module.java
Also fix issue where prerequisite tree doesn't load on startup
=> Remove unnecessary references to CheckCommand

src/main/java/seedu/address/model/ModulesInfo.java
=> Add method to get module code strings from ModulesInfo

src/main/java/seedu/address/logic/commands/exceptions/CommandException.java, src/main/java/seedu/address/model/ModulesInfo.java, src/test/java/seedu/address/logic/commands/CommandTestUtil.java, src/test/java/seedu/address/logic/commands/verification/DescriptionCommandTest.java, src/test/java/seedu/address/logic/commands/verification/ValidModsCommandTest.java, src/test/java/seedu/address/model/ModulesInfoTest.java
Added tests for `DescriptionCommand` and `ValidModsCommand`. Ready to be merged
=> Add tests for verification commands

src/main/java/seedu/address/logic/LogicManager.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ModulePlanner.java, src/main/java/seedu/address/model/studyplan/StudyPlan.java, src/main/java/seedu/address/ui/MainWindow.java, src/main/resources/view/MainWindow.fxml, src/test/java/seedu/address/logic/commands/datamanagement/CreateTagCommandTest.java, src/test/java/seedu/address/logic/commands/verification/DescriptionCommandTest.java, src/test/java/seedu/address/logic/commands/verification/ValidModsCommandTest.java
This resolves #181, ready to be merged
=> Add displaying of MC count for study plan

src/main/java/seedu/address/model/ModulePlanner.java, src/main/java/seedu/address/model/module/Module.java
=> Fix empty "NEEDS:" label when starting with a sample study plan

src/main/java/seedu/address/logic/commands/verification/CheckCommand.java, src/main/java/seedu/address/logic/parser/ModulePlannerParser.java, src/main/java/seedu/address/model/studyplan/StudyPlan.java, src/main/java/seedu/address/model/studyplan/StudyPlanVerificationHelper.java, src/test/java/seedu/address/logic/commands/CheckCommandTest.java, src/test/java/seedu/address/logic/commands/verification/DescriptionCommandTest.java, src/test/java/seedu/address/model/studyplan/StudyPlanTest.java
=> Add check command and tests

src/main/java/seedu/address/logic/commands/cli/AddModuleCommand.java, src/main/java/seedu/address/logic/commands/cli/DeleteModuleCommand.java
=> Fix message usage for add and delete module command

src/main/java/seedu/address/logic/commands/gui/HelpCommand.java, src/main/java/seedu/address/logic/commands/verification/ClearInvalidModsCommand.java, src/main/java/seedu/address/logic/parser/ModulePlannerParser.java, src/main/java/seedu/address/logic/parser/gui/HelpCommandParser.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ModulePlanner.java, src/main/java/seedu/address/model/studyplan/StudyPlan.java, src/main/java/seedu/address/ui/Autocomplete.java, src/test/java/seedu/address/logic/commands/CheckCommandTest.java, src/test/java/seedu/address/logic/commands/HelpCommandTest.java, src/test/java/seedu/address/logic/commands/verification/ClearInvalidModsCommandTest.java, src/test/java/seedu/address/logic/commands/verification/DescriptionCommandTest.java, src/test/java/seedu/address/logic/commands/verification/ValidModsCommandTest.java, src/test/java/seedu/address/model/studyplan/StudyPlanTest.java
=> Add command to clear invalid mods

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/verification/ValidModsCommand.java, src/main/java/seedu/address/model/Model.java, src/main/java/seedu/address/model/ModelManager.java, src/main/java/seedu/address/model/ModulePlanner.java, src/main/java/seedu/address/model/studyplan/StudyPlan.java, src/test/java/seedu/address/logic/commands/CheckCommandTest.java, src/test/java/seedu/address/logic/commands/verification/ClearInvalidModsCommandTest.java, src/test/java/seedu/address/logic/commands/verification/DescriptionCommandTest.java, src/test/java/seedu/address/logic/commands/verification/ValidModsCommandTest.java, src/test/java/seedu/address/model/studyplan/StudyPlanTest.java
=> Update validmods description and display

docs/UserGuide.adoc
=> Update user guide for description command

docs/UserGuide.adoc, src/main/java/seedu/address/logic/commands/datamanagement/ShowCommand.java, src/main/java/seedu/address/logic/commands/datamanagement/ShowCoreCommand.java, src/main/java/seedu/address/logic/commands/datamanagement/ShowFocusCommand.java, src/main/java/seedu/address/logic/commands/gui/HelpCommand.java, src/main/java/seedu/address/logic/parser/ModulePlannerParser.java, src/main/java/seedu/address/logic/parser/gui/HelpCommandParser.java, src/main/java/seedu/address/ui/ModulePlannerAutocompleteSearch.java, src/test/java/seedu/address/logic/commands/datamanagement/ShowCoreCommandTest.java, src/test/java/seedu/address/logic/commands/datamanagement/ShowFocusCommandTest.java
psps added 2 new commands `showcore` and `showfocus`, I've added tests and added them to help, autocomplete, and user guide also.
=> Add show commands
